### ISSUE TITLE
snapshot time name

### ISSUE THREAD

**Issue by unix1984** [yoshtec/snapbtrex#20]
Hello

I only have one question. The Script is working properly.

At 23:45 the script starts every day.
crontab: 45  23  * * *

Yet he is 2 hours earlier in the name of snapshots.
20210601-214547: EXEC  >-> sudo btrfs subvolume snapshot -r /mnt/sda3/containers/alpine-lighttpd /mnt/sda3/autosnap/alpine-lighttpd/20210601-214547

**23:45 VS 21:45**

How can i set the exact time on behalf of the snapshot?

Thank you very much in advance for your help!

Regards

**Comment by yoshtec** [comment]
Hi,

this is on purpose. The snapshot is always named by [UTC](https://en.wikipedia.org/wiki/Coordinated_Universal_Time) time. As such the path is safe of misinterpretation of daylight saving time (as it's common in Europe) and is also safe to be transferred across systems in different timezones, or if you change the Timezone on your device (i.e. laptop during travel).

You could change the behaviour by changing the `time.gmtime()` calls to `time.localtime()` if you really know what you're doing. (Warning: This could lead to pruning of younger directories, when called multiple times during DST changes.)

**Comment by unix1984** [comment]
Hello,

thanks i will try.
I changed the following 2 lines:

`return time.strftime(DATE_FORMAT, time.localtime(secs))`

and

`tt = time.strftime(DATE_FORMAT, time.localtime(None)) + ": "`

I'll see how it works in the evening.

Thanks!

**Comment by unix1984** [comment]
Super! Works perfect!
